### ISSUE TITLE
I think you got a typo in chapter 2

### ISSUE THREAD

**Issue by heron2014** [iteles/Javascript-the-Good-Parts-notes#11]
Under Numbers : 
use isNan(numbers) to check for NaNs (  instead of isNaN(numbers)   )

**Comment by nelsonic** [comment]
Well spotted @heron2014 
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/isNaN
Please submit a **pull request** with the correction. :+1:

**Comment by iteles** [comment]
What @nelsonic said :wink:

**Comment by iteles** [comment]
Fixed by @heron2014 in PR #12
