### ISSUE TITLE
Question on Functional Section of Chapter Inheritance (Page54)

### ISSUE THREAD

**Issue by snowshine09** [iteles/Javascript-the-Good-Parts-notes#13]
Hi Why the author would recommend to wrap the function in another shell of super_get_name instead of calling it directly? Thanks!

**Comment by iteles** [comment]
Hi @snowshine09! So sorry, I read your issue and as there's no way to mark issues as 'unread' again on github, I completely forgot to give you a real answer.

Here's the best answer I found when I was searching at the time I was reading: http://stackoverflow.com/questions/21332306/understanding-the-superior-method-introduced-by-crockford

If you'd like to submit a pull request (PR) to the notes, it would certainly be much appreciated by people reading them :blush:

**Comment by iteles** [comment]
@snowshine09 Please re-open this issue if you feel you need more explanation.

Many thanks
Ines

**Comment by nelsonic** [comment]
I don't *get* it...

**Comment by iteles** [comment]
@nelsonic Are you saying this needs a PR to the notes in your opinion?

**Comment by iteles** [comment]
This issue was moved to iteles/learn-huxley#2
