### ISSUE TITLE
Contributing to these notes & discussing contributions

### ISSUE THREAD

**Issue by besarthoxhaj** [iteles/Javascript-the-Good-Parts-notes#2]
Hi @iteles! I'm reading and studying Javascript the good parts! 
As most of the people I started to write my own notes. Well... we all know how it goes, the starting point is cool! Write a couple of chapters maybe some examples but after a week or two, I will probably stop leaving it incomplete!

For this reason I would like to contribute to your notes, adding examples and few bits here and there.

What do you think? Would a gitter channel work well for discussing pull requests?

**Comment by iteles** [comment]
@besarthoxhaj This sounds like a great idea - I know exactly what you mean, mine are somewhat incomplete too!
Unless they're super complicated pull requests, I reckon we can just discuss them in the comments as we go along? i.e. You submit a pull request, I'll comment whether I agree or not and merge accordingly - then all the history of each pull request is documented on Github as it should be ;) Good practice for projects!

What do you think?

**Comment by iteles** [comment]
Agreed verbally. Closing this issue and adding a note on this to readme ( #5 )
