### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by ghost** [iteles/Javascript-the-Good-Parts-notes#25]
"Strings
16-bit character set and don't have character types.
Backslashes () are used for escaping characters that could cause problems in strings.
Strings are immutable."

Question: That means that i can use backslash instead of a character to avoid problems in our code? An example would be very appreciated!! Thank you

**Comment by nelsonic** [comment]
Single quotes are often used to define a String in JavaScript, but if a person's name has an apostrophe (_and the **developer** does not know the difference between an apostrophe and single quote_) it is _useful_ to "escape" the apostrophe character: 
```js
var name = 'Patrick O\'Brian'; // using a backslash in front of the apostrophe
console.log('name:', name); // name: Patrick O'Brian
```
> Try it: https://repl.it/Hu5L

further reading: https://webdesignledger.com/common-typography-mistakes-apostrophes-versus-quotation-marks
![image](https://cloud.githubusercontent.com/assets/194400/25989405/e47ff6aa-36f3-11e7-9e3d-c7a3da6f1872.png)

**Comment by ghost** [comment]
Big thank you @nelsonic 🥇

**Comment by nelsonic** [comment]
@edwardcodes please remember to _close_ issues when they are "resolved" 
(_or in the case of a question, when the answer is satisfactory_) 👍

**Comment by iteles** [comment]
@edwardcodes Great question! If you think the notes can be clarified, please do put in a pull request (we can pair over google hangouts if you haven't done it before 😊 )

**Comment by nelsonic** [comment]
@edwardcodes seriously though, a Pull Request is a _much_ better "_outcome_" than simply closing the issue... 🤔

**Comment by ghost** [comment]
@nelsonic i agree!

**Comment by nelsonic** [comment]
@edwardcodes do you want to do a Google Hangout at some point today 
to go through creating the Pull Request?

**Comment by iteles** [comment]
@edwardcodes Can we close this issue now if you think it has been resolved by your PR? 😊
