### ISSUE TITLE
Is prototypal inheritance good or bad?

### ISSUE THREAD

**Issue by sapegin** [iteles/Javascript-the-Good-Parts-notes#31]
> The best parts of Javascript include…
>
> The worst parts include…
> 
> Javascript has a class free object makeup, relying instead on objects inheriting properties directly from other objects - this is prototypal inheritance.

Is prototypal inheritance good or bad? And what is _object makeup_?

**Comment by nelsonic** [comment]
@sapegin we typically avoid prototypal inheritance in JS code wherever possible
_because_ it can result in _unpredictable_ behaviour. 
We _prefer_ to write _purely_ `functional` code to eliminate "side effects".

**Comment by sapegin** [comment]
Who are _we_? ;-)

**Comment by nelsonic** [comment]
_We_ are the people who write JS code at @iteles software company @dwyl 😉 
where messing with Prototypes is a "code smell". 💩 
If a feature can be built/shipped _without complex_ code, why over-complicate it? 🤔
