### ISSUE TITLE
Transfer this repo to dwyl?

### ISSUE THREAD

**Issue by iteles** [iteles/Javascript-the-Good-Parts-notes#33]
I believe this would be a good addition to dwyl, if we include a disclaimer to make it clear that these are notes from the book, which was written _before_ es6 and all the new-fangled fun.

@nelsonic, what do you think? Good for the dwyl archive?

**Comment by nelsonic** [comment]
@iteles I've transferred all of "_my_" learning to dwyl ... 
I feel that it makes _collaboration_/_contribution_ easier. 

up to you. 👍
