### ISSUE TITLE
# 🤷‍♂️ don't know much about GitHub. 
I m learning things , i wanted a copy of that javascript link into mt account do i can use it to study .

### ISSUE THREAD

**Issue by Anshulmiller** [iteles/Javascript-the-Good-Parts-notes#39]
# 🤷‍♂️ 

_Originally posted by @nelsonic in https://github.com/dwyl/Javascript-the-Good-Parts-notes/issues/38#issuecomment-841243674_

**Comment by nelsonic** [comment]
@Anshulmiller you're probably looking for the Star and/or Fork button in the top-right corner: ↗️ 
![star-js-good-parts](https://user-images.githubusercontent.com/194400/118357056-06cd1400-b570-11eb-92a4-99f2fc21541e.gif)

Then you will have a bookmark for it in your "stars": https://github.com/Anshulmiller?tab=stars
