### ISSUE TITLE
Review, round out and tidy up notes

### ISSUE THREAD

**Issue by iteles** [iteles/Javascript-the-Good-Parts-notes#7]
Aside from closing the open question ( #6 ), these notes need one final review for clarifications, simplifications, catching typos and various places where these could be enhanced.

**Comment by nelsonic** [comment]
@iteles I would still include the photo of the book with tabs as an intro image...

**Comment by iteles** [comment]
@nelsonic :+1: I'll make it smaller and include :)

**Comment by ericguedespinto** [comment]
It would be a good idea to review what Crockford has been saying since the release of his book in 2000. Things like not using null or this and also class free inheritance (the better parts)

**Comment by nelsonic** [comment]
@ericguedespinto agree 100%! we've been meaning to do this for a while!
https://www.youtube.com/watch?v=bo36MrBfTk4
It's _rare_ to find a fellow _Good Parts_ Follower in 2016! 😉

**Comment by iteles** [comment]
Good point @ericguedespinto If you have time to PR some of that in, please do so 😊

**Comment by iteles** [comment]
No longer relevant as this book has likely been superseded.
